spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microsevicecloud-config-dev
---
spring:
  profiles: test #测试环境
  application:
    name: microsevicecloud-config-test